sudo: false
language: ruby
rvm:
- 2.3.1
before_install:
- gem install bundler -v 1.15.4
- ./pull_mulang.sh
deploy:
  provider: rubygems
  api_key:
    secure: vKSVp//78sPnV1GL4a06ZyLfww7iET0E/85yTZGM82u6INMvTimQZjAgLgTndn5xSkjyhGtzpEaIGnHNyIXPf2DkbF+qOsyH7KvfdZjDTkWpnY0BNlhcuvYpNjFS74IznL2R9+z08LBQ8ypa5HAj80pjc6QYAGgkzO8VUAThYzXZwb1Xu5Mi02+i0KwEvpbm6jIiz9cFG+gMkrmTZBd26If66xzX0Bfc2HD+4ctEx5PO4mVWEjRa8C9JLOMoKlvLnSSVexg9y1gdtQqM56jwDZiYej4OY4fJpbjsi2mO/6MSgmRzSu14MWkp72oAnfq5POnDQhEI6y5WDQaLRCXSGgpvXXoYJTRr1PIi8nG1VwqPco8592nvWNSPnBQ5Lts3BcCl+CW35LZXM7vAeMCywE1SxteZrra5Fv8KOz6f074qbIZm1X8giGs04subTB+/a78/6/XgbKBO9dWp5Y6YTO0AVPo2EU4ZcFthZgDqEXxZlw++TeBOVbsAxtK7C1YIl1bfi9xJ8GIxzuKY3el0crOyLnB110J63Wu4+YUk+CWUItISEFz4hm2UCRZXY95OH3cc6YqfYiSAsIcu5M4i9B/N7hM1iSgC04GhNqmNpbbKk65RoUvU17I0+uq9nDc0hUaktsYcmS6qnEwfMuKC1R+brUrVHBjgy6794nj+j/Y=
  gem: mulang
  on:
    tags: true
    repo: mumuki/mulang.rb
